version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rss25sb_postgres
    environment:
      POSTGRES_DB: rss25sb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rss25sb_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.3
    container_name: rss25sb_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'True'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rss25sb_network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  rss25sb_network:
    driver: bridge
